// export { default as HomePage } from "./HomePage/HomePage";
// export { default as AboutPage } from "./AboutPage/AboutPage";
// export { default as BlogSingle } from "./Blog";
// export { default as BlogSidebar } from "./Blog";
// export { default as SignIn } from "./SignIn/SignIn";
// export { default as Error } from "./Error/Error";
// export { default as BlogGrid } from "./Blog";
// export { default as Register } from "./Register/Register";
// export { default as Contact } from "./Contact/Contact";
export * from "./HomePage";
export * from "./Blog";
export * from "./Register";
export * from "./SignIn";
export * from "./AboutPage";
export * from "./Contact";
export * from "./Error";
