export { default as HomePage } from "./HomePage/HomePage";
export { default as AboutPage } from "./AboutPage/AboutPage";
export { default as BlogSingle } from "./BlogSingle/BlogSingle";
export { default as BlogSidebar } from "./BlogSidebar/BlogSidebar";
export { default as SignIn } from "./SignIn/SignIn";
export { default as Error } from "./Error/Error";
export { default as BlogGrid } from "./BlogGrid/BlogGrid";
export { default as Register } from "./Register/Register";
export { default as Contact } from "./Contact/Contact";
