import { images } from "../../constants";

const blogData = [
  {
    id: 1,
    blogImg: `${images.blog1}`,
    category: "Computer",
    title: "Best UI components for modern websites ",
    url: "/blog-detail",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet dictum neque, laoreet dolor..",
    author: "Samuyl Joshi",
    authorImage: `${images.author1}`,
    job: "Graphic Designer",
    date: "15 Oct, 2023",
  },
  {
    id: 2,
    blogImg: `${images.blog2}`,
    category: "Design",
    title: "9 simple ways to improve your design skills ",
    url: "/blog-sidebar",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet dictum neque, laoreet dolor..",
    author: "Victori Umaru",
    authorImage: `${images.author2}`,
    job: "Content Writer",
    date: "20 Nov, 2023",
  },
  {
    id: 3,
    blogImg: `${images.blog3}`,
    category: "Computer",
    title: "Tips to quickly improve your coding speed. ",
    url: "/blog-detail",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet dictum neque, laoreet dolor..",
    author: "Ashrof Salman",
    authorImage: `${images.author3}`,
    job: "Web Developer",
    date: "25 Dec, 2023",
  },
  {
    id: 4,
    blogImg: `${images.blog1}`,
    category: "Computer",
    title: "Best UI components for modern websites ",
    url: "/blog-sidebar",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet dictum neque, laoreet dolor..",
    author: "Samuyl Joshi",
    authorImage: `${images.author1}`,
    job: "Graphic Designer",
    date: "15 Oct, 2023",
  },
  {
    id: 5,
    blogImg: `${images.blog2}`,
    category: "Design",
    title: "9 simple ways to improve your design skills ",
    url: "/blog-detail",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet dictum neque, laoreet dolor..",
    author: "Victori Umaru",
    authorImage: `${images.author2}`,
    job: "Content Writer",
    date: "20 Nov, 2023",
  },
  {
    id: 6,
    blogImg: `${images.blog3}`,
    category: "Computer",
    title: "Tips to quickly improve your coding speed. ",
    url: "/blog-sidebar",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet dictum neque, laoreet dolor..",
    author: "Ashrof Salman",
    authorImage: `${images.author3}`,
    job: "Web Developer",
    date: "25 Dec, 2023",
  },
];

export default blogData;
